en:
  - title: Overview
    name: Docs
    items:
      - title: Introduction
        name: Introduction
      - title: Installation
        name: Installation
      - title: Quickstart
        name: Quickstart
      - title: Internationalization
        name: i18n
      - title: Change Log
        name: Changelog
  - title: Components
    name: Docs
    groups:
      - title: Base
        items:
          - title: Button
            name: Button
          - title: Layout
            name: Layout
          - title: Tag
            name: Tag
          - title: Icon
            name: Icon
      - title: Form
        items:
          - title: Checkbox
            name: Checkbox
          - title: Input
            name: Input
          - title: InputNumber
            name: InputNumber
          - title: Radio
            name: Radio
          - title: Select
            name: Select
          - title: Switch
            name: Switch
          - title: Slider
            name: Slider
          - title: Textarea
            name: Textarea
      - title: View
        items:
          - title: Alert
            name: Alert
          - title: Badge
            name: Badge
          - title: LoadingBar
            name: LoadingBar
          - title: Modal
            name: Modal
          - title: Message
            name: Message
          - title: Notification
            name: Notification
          - title: Popover
            name: Popover
          - title: Progress
            name: Progress
          - title: Tooltip
            name: Tooltip
          - title: Table
            name: Table
      - title: Navigation
        items:
          - title: Breadcrumb
            name: Breadcrumb
          - title: Dropdown
            name: Dropdown
          - title: Menu
            name: Menu
          - title: Pagination
            name: Pagination
