en:
  - title: Guide
    name: Guide
    items:
      - title: Quickstart
        name: Quickstart
      - title: Custom Templates
        name: customtemplates
      - title: Vue 1.x
        name: Vue1
      - title: Textarea
        name: Textarea
      - title: Props
        name: Props
  - title: Notes
    name: Notes
    items:
      - title: FAQ
        name: FAQ
      - title: Change Log
        name: Changelog
